### ISSUE TITLE
Two test_util failures in 1.10.0

### ISSUE THREAD

**Issue by koobs** [python-twitter-tools/twitter#166]
Picked up the following two test failures while updating the FreeBSD port for twitter-tools:

```
======================================================================
FAIL: tests.test_util.test_follow_redirects_filtered_by_site_after_redirect
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/home/user/repos/freebsd/ports/net/py-twitter-tools/work/sixohsix-twitter-f56d4b3/tests/test_util.py", line 107, in test_follow_redir
ects_filtered_by_site_after_redirect
    assert filtered == follow_redirects(url(link), hosts)
AssertionError


======================================================================
FAIL: tests.test_util.test_follow_redirects_filtered_by_site_allowed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/home/user/repos/freebsd/ports/net/py-twitter-tools/work/sixohsix-twitter-f56d4b3/tests/test_util.py", line 116, in test_follow_redir
ects_filtered_by_site_allowed
    assert url(redirected) == follow_redirects(url(link), hosts)
AssertionError

----------------------------------------------------------------------
Ran 17 tests in 14.026s

FAILED (failures=2)
```

**Comment by koobs** [comment]
In version 1.17.1, a number of additional tests are now failing in test_util. I've managed to get some additional information by running nosetests -d,  and running tests under py.test.

current-amd64 is the machines hostname

```
    def test_follow_redirects_redirected_link():
        redirected = "/redirected"
        link = "/resource"
        with start_server(
            Response(link, 301, {"Location": redirected}),
            Response(redirected, 200, {})) as url:
>           assert url(redirected) == follow_redirects(url(link))
E           assert 'http://curre...50/redirected' == 'http://curren...4250/resource'
E             - http://current-amd64:44250/redirected
E             ?                              ^^  ----
E             + http://current-amd64:44250/resource
E             ?                              ^^^ +

tests/test_util.py:69: AssertionError
```
```
    def test_follow_redirects_link_to_last_available():
        unavailable = "/unavailable"
        link = "/resource"
        with start_server(
            Response(link, 301, {"Location": unavailable}),
            Response(unavailable, 404, {})) as url:
>           assert url(unavailable) == follow_redirects(url(link))
E           assert 'http://curre...2/unavailable' == 'http://curren...4252/resource'
E             - http://current-amd64:44252/unavailable
E             ?                             ^^^^^^^^^
E             + http://current-amd64:44252/resource
E             ?                            ++++ ^^

tests/test_util.py:82: AssertionError
```
```
    def test_follow_redirects_link_to_nowhere():
        unavailable = "http://links.nowhere/"
        link = "/resource"
        with start_server(
            Response(link, 301, {"Location": unavailable})) as url:
>           assert unavailable == follow_redirects(url(link))
E           assert 'http://links.nowhere/' == 'http://current-amd64:44253/resource'
E             - http://links.nowhere/
E             + http://current-amd64:44253/resource

tests/test_util.py:94: AssertionError
```
```
    def test_follow_redirects_filtered_by_site_after_redirect():
        link = "/resource"
        redirected = "/redirected"
        filtered = "http://dont-follow/"
        with start_server(
            Response(link, 301, {"Location": redirected}),
            Response(redirected, 301, {"Location": filtered})) as url:
            hosts = [socket.gethostname().lower()]
>           assert filtered == follow_redirects(url(link), hosts)
E           assert 'http://dont-follow/' == 'http://current-amd64:44255/resource'
E             - http://dont-follow/
E             + http://current-amd64:44255/resource

tests/test_util.py:110: AssertionError
```
```
    def test_follow_redirects_filtered_by_site_allowed():
        redirected = "/redirected"
        link = "/resource"
        with start_server(
            Response(link, 301, {"Location": redirected}),
            Response(redirected, 200, {})) as url:
            hosts = [socket.gethostname().lower()]
>           assert url(redirected) == follow_redirects(url(link), hosts)
E           assert 'http://curre...56/redirected' == 'http://curren...4256/resource'
E             - http://current-amd64:44256/redirected
E             ?                              ^^  ----
E             + http://current-amd64:44256/resource
E             ?                              ^^^ +

tests/test_util.py:119: AssertionError
```
```
    def test_expand_line():
        redirected = "/redirected"
        link = "/resource"
        with start_server(
            Response(link, 301, {"Location": redirected}),
            Response(redirected, 200, {})) as url:
            fmt = "before %s after"
            line = fmt % url(link)
            expected = fmt % url(redirected)
>           assert expected == expand_line(line, None)
E           assert 'before http:...irected after' == 'before http:/...esource after'
E             - before http://current-amd64:44257/redirected after
E             ?                                     ^^  ----
E             + before http://current-amd64:44257/resource after
E             ?                                     ^^^ +

tests/test_util.py:130: AssertionError
```

These appear to be issues with `follow_redirects` ?

**Comment by hugovk** [comment]
Thanks for the report, however we're no longer maintaining this project and will be archiving it.

The existing releases and code will remain available in their current state.
