### ISSUE TITLE
New but continuing Json error - "ValueError: Unterminated string starting at:..."

### ISSUE THREAD

**Issue by kelley8732** [python-twitter-tools/twitter#256]
Hi,

Great program. It has been a real saver at times. I have been running it successfully for around 2 months in combination with some other tools that fit my needs.

2 weeks ago I started to get json errors. Am I the only one?
## Here is an example of the error:

Traceback (most recent call last):
  File "/home/k/projects/Tweeter.py", line 548, in <module>
    runengine_for_full_retweets()
  File "/home/k/projects/Tweeter.py", line 161, in runengine_for_full_retweets
    twittersearch = t.statuses.user_timeline(screen_name=i) ## i becomes variable for entire return of timeline tweets##
  File "/usr/local/lib/python3.2/dist-packages/twitter/api.py", line 245, in **call**
    return self._handle_response(req, uri, arg_data, _timeout)
  File "/usr/local/lib/python3.2/dist-packages/twitter/api.py", line 267, in _handle_response
    res = json.loads(data.decode('utf8'))
  File "/usr/lib/python3.2/json/__init__.py", line 309, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.2/json/decoder.py", line 353, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.2/json/decoder.py", line 369, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 35495 (char 35495)

> > > ---
> > > 
> > > I am new to the language and even newer to github. Any help at all would be greatly appreciated.

**Comment by apokalyptik** [comment]
I was getting:

```
Traceback (most recent call last):
  File "/tmp/tmp.209Fq5S2cy/fetch.py", line 148, in <module>
    exit(main())
  File "/tmp/tmp.209Fq5S2cy/fetch.py", line 136, in main
    print(latest_stable_version(get))
  File "/tmp/tmp.209Fq5S2cy/fetch.py", line 85, in latest_stable_version
    'https://pypi.python.org/pypi/certbot/json')).decode('UTF-8'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 806 column 25 (char 48399)
WARNING: unable to check for updates.
```

Running `apt-get install pypy-setuptools` fixed this error for me (debian 9.4 (stretch))
