### ISSUE TITLE
Twitterbot error

### ISSUE THREAD

**Issue by metaltermite** [python-twitter-tools/twitter#275]
Just installed everything as per instructions. Executed twitterbot, and it returns the following error

Traceback (most recent call last):
  File "/usr/local/bin/twitterbot", line 9, in <module>
    load_entry_point('twitter==1.15.0', 'console_scripts', 'twitterbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "build/bdist.linux-i686/egg/twitter/ircbot.py", line 84, in <module>
  File "build/bdist.linux-i686/egg/irclib.py", line 1188, in <module>
AttributeError: type object 'str' has no attribute 'maketrans'

**Comment by aisayko** [comment]
irclib implemented only for Python3?

**Comment by zodman** [comment]
use the python-irclib it works for me

**Comment by hugovk** [comment]
Thanks for the report, however we're no longer maintaining this project and will be archiving it.

The existing releases and code will remain available in their current state.
