### ISSUE TITLE
UnboundLocalError when trying to view Twitter list

### ISSUE THREAD

**Issue by j605** [python-twitter-tools/twitter#372]
To reproduce do, 
```sh
twitter mylist list
```
This is the stacktrace I get,
```python
Traceback (most recent call last):
  File "/usr/bin/twitter", line 11, in <module>
    load_entry_point('twitter==1.18.0', 'console_scripts', 'twitter')()
  File "/usr/lib/python3.6/site-packages/twitter/cmdline.py", line 793, in main
    Action()(twitter, options)
  File "/usr/lib/python3.6/site-packages/twitter/cmdline.py", line 445, in __call__
    doAction()
  File "/usr/lib/python3.6/site-packages/twitter/cmdline.py", line 438, in <lambda>
    doAction = lambda: action(twitter, options)
  File "/usr/lib/python3.6/site-packages/twitter/cmdline.py", line 462, in __call__
    statuses = self.getStatuses(twitter, options)
  File "/usr/lib/python3.6/site-packages/twitter/cmdline.py", line 535, in getStatuses
    return ListsAction.getStatuses(self, twitter, options)
  File "/usr/lib/python3.6/site-packages/twitter/cmdline.py", line 525, in getStatuses
    return list(reversed(twitter.lists.statuses(
UnboundLocalError: local variable 'list' referenced before assignment
```
I was not able to see what is causing this error as  `list` is a proper python keyword and it has not been redefined in that scope.

**Comment by RouxRC** [comment]
Nice catch
Can you try to change in /usr/lib/python3.6/site-packages/twitter/cmdline.py the variable "list" into "lst" on lines 520 and 522 and see if that solves it ?

**Comment by j605** [comment]
I got a different error this time probably due to change in the API. If I just specify the name of the list I get,
```python
details: {'errors': [{'code': 112, 'message': 'You must specify either a list ID or a slug and owner.'}]}
```

I follow a list for which I am not the owner so it might be triggering this error.

**Comment by RouxRC** [comment]
I don't know whether the cli tools have a way to access those. You can easily write python code to do so following the main readme and looking at the api documentation https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-statuses
