### ISSUE TITLE
Latin caracters crash the twitter bot

### ISSUE THREAD

**Issue by onilton** [python-twitter-tools/twitter#42]
If you try to do 

twitter -c configfile set "Status ç á é i ô ê a"

You get:
Traceback (most recent call last):
  File "/usr/local/bin/twitter", line 9, in <module>
    load_entry_point('twitter==1.6.1', 'console_scripts', 'twitter')()
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.6.1-py2.6.egg/twitter/cmdline.py", line 597, in main
    Action()(twitter, options)
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.6.1-py2.6.egg/twitter/cmdline.py", line 351, in **call**
    doAction()
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.6.1-py2.6.egg/twitter/cmdline.py", line 345, in <lambda>
    doAction = lambda : action(twitter, options)
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.6.1-py2.6.egg/twitter/cmdline.py", line 461, in **call**
    twitter.statuses.update(status=statusTxt)
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.6.1-py2.6.egg/twitter/api.py", line 145, in **call**
    arg_data = self.auth.encode_params(uriBase, method, kwargs)
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.6.1-py2.6.egg/twitter/oauth.py", line 63, in encode_params
    enc_params = urlencode_noplus(sorted(params.items()))
  File "/usr/local/lib/python2.6/dist-packages/twitter-1.6.1-py2.6.egg/twitter/oauth.py", line 95, in urlencode_noplus
    v = v.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)

I'm using Ubuntu 10.04. And I discovered this bug using the library itself. But just to prove it was a library related and not a bug in my program a used the official twitter in terminal that comes with the library

If I can help with anything else, just tell! :)

Thanks!

**Comment by hugovk** [comment]
Thanks for the report, however we're no longer maintaining this project and will be archiving it.

The existing releases and code will remain available in their current state.
