### ISSUE TITLE
HTMLParser' object has no attribute 'unescape'

### ISSUE THREAD

**Issue by tyjak** [python-twitter-tools/twitter#423]
With python 3.9 I encountered this error : `AttributeError: 'HTMLParser' object has no attribute 'unescape'`.
In ptyhon 3.9 unerscape was [remove from HTMLParser](https://docs.python.org/3/whatsnew/3.9.html#porting-to-python-3-9).

```python
Traceback (most recent call last):
  File "/usr/bin/twitter", line 33, in <module>
    sys.exit(load_entry_point('twitter==1.18.0', 'console_scripts', 'twitter')())
  File "/usr/lib/python3.9/site-packages/twitter/cmdline.py", line 793, in main
    Action()(twitter, options)
  File "/usr/lib/python3.9/site-packages/twitter/cmdline.py", line 445, in __call__
    doAction()
  File "/usr/lib/python3.9/site-packages/twitter/cmdline.py", line 438, in <lambda>
    doAction = lambda: action(twitter, options)
  File "/usr/lib/python3.9/site-packages/twitter/cmdline.py", line 465, in __call__
    statusStr = sf(status, options)
  File "/usr/lib/python3.9/site-packages/twitter/cmdline.py", line 229, in __call__
    gHtmlParser.unescape(correctRTStatus(status))))
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

**Comment by dijatool** [comment]
Can someone on this thread, admin or someone, please be sure that dely@dijatool.com or ely@dijas.com is removed entirely from any notifications? My husband David is deceased.

**Comment by boogheta** [comment]
Hi @dijatool, like I answered before, only you can unsubscribe from these notifications, please look at the explanations I gave you earlier here: https://github.com/python-twitter-tools/twitter/pull/426#issuecomment-751344011
