### ISSUE TITLE
Twitterbot dies after reading (malformed?) status update

### ISSUE THREAD

**Issue by geeknik** [python-twitter-tools/twitter#62]
Our twitterbot has been pretty stable until I went out of town and got an email saying it was missing from our IRC channel.  I checked the screen session it runs it and found this:

URLError: <urlopen error [Errno 8] _ssl.c:503: EOF occurred in violation of protocol>
Exception while querying twitter:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twitter/ircbot.py", line 167, in check_statuses
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 167, in **call**
    return self._handle_response(req, uri, arg_data)
  File "/usr/local/lib/python2.7/dist-packages/twitter/api.py", line 171, in _handle_response
    handle = urllib_request.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1209, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1174, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1027, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

Any thoughts?

**Comment by hugovk** [comment]
Thanks for the report, however we're no longer maintaining this project and will be archiving it.

The existing releases and code will remain available in their current state.
