### ISSUE TITLE
Errors & Connection Failures

### ISSUE THREAD

**Issue by NonaSuomy** [python-twitter-tools/twitter#73]
Windows 7 64bit
Python 2.7
Current code on the github

error usually seemed to be caused if the connection goes unstable. Bot leaves channel but python script is still running forced to quit it then reload to join again.

If I wanted the bot to monitor all of twitter without following people for keywords what would this be called and how would I go about doing that?

  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] A connection attempt failed because the c
onnected party did not properly respond after a period of time, or established c
onnection failed because connected host has failed to respond>
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] A connection attempt failed because the c
onnected party did not properly respond after a period of time, or established c
onnection failed because connected host has failed to respond>
^C

C:\Python27\Scripts\sixohsix-twitter-0cced44>twitterbot "C:\BAKPython27\Lib\site
-packages\twitterbot.ini"
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in **call**
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 173, in _handle_response

```
res = json.loads(handle.read().decode('utf8'))
```

  File "C:\Python27\lib\socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "C:\Python27\lib\httplib.py", line 561, in read
    s = self.fp.read(amt)
  File "C:\Python27\lib\socket.py", line 380, in read
    data = self._sock.recv(left)
  File "C:\Python27\lib\ssl.py", line 241, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 160, in read
    return self._sslobj.read(len)
error: [Errno 10054] An existing connection was forcibly closed by the remote ho
st
^C

C:\Python27\Scripts\sixohsix-twitter-0cced44>twitterbot "C:\BAKPython27\Lib\site
-packages\twitterbot.ini"
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in **call**
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1030, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 173, in _handle_response

```
res = json.loads(handle.read().decode('utf8'))
```

  File "C:\Python27\lib\json__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 171, in _handle_response

```
handle = urllib_request.urlopen(req)
```

  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
Exception while querying twitter:
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\twitter\ircbot.py", line 168, in check_statuse
s
    updates = reversed(self.twitter.statuses.friends_timeline())
  File "build\bdist.win-amd64\egg\twitter\api.py", line 167, in __call__
    return self._handle_response(req, uri, arg_data)
  File "build\bdist.win-amd64\egg\twitter\api.py", line 173, in _handle_response

```
res = json.loads(handle.read().decode('utf8'))
```

  File "C:\Python27\lib\json__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
^CException KeyboardInterrupt in <module 'threading' from 'C:\Python27\lib\threa
ding.pyc'> ignored

**Comment by hugovk** [comment]
Thanks for the report, however we're no longer maintaining this project and will be archiving it.

The existing releases and code will remain available in their current state.
